name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - run: ./scripts/test.py
